/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateGresubjectscoreArgs } from "./CreateGresubjectscoreArgs";
import { UpdateGresubjectscoreArgs } from "./UpdateGresubjectscoreArgs";
import { DeleteGresubjectscoreArgs } from "./DeleteGresubjectscoreArgs";
import { GresubjectscoreCountArgs } from "./GresubjectscoreCountArgs";
import { GresubjectscoreFindManyArgs } from "./GresubjectscoreFindManyArgs";
import { GresubjectscoreFindUniqueArgs } from "./GresubjectscoreFindUniqueArgs";
import { Gresubjectscore } from "./Gresubjectscore";
import { GresubjectscoreService } from "../gresubjectscore.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Gresubjectscore)
export class GresubjectscoreResolverBase {
  constructor(
    protected readonly service: GresubjectscoreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "read",
    possession: "any",
  })
  async _gresubjectscoresMeta(
    @graphql.Args() args: GresubjectscoreCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Gresubjectscore])
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "read",
    possession: "any",
  })
  async gresubjectscores(
    @graphql.Args() args: GresubjectscoreFindManyArgs
  ): Promise<Gresubjectscore[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Gresubjectscore, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "read",
    possession: "own",
  })
  async gresubjectscore(
    @graphql.Args() args: GresubjectscoreFindUniqueArgs
  ): Promise<Gresubjectscore | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gresubjectscore)
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "create",
    possession: "any",
  })
  async createGresubjectscore(
    @graphql.Args() args: CreateGresubjectscoreArgs
  ): Promise<Gresubjectscore> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gresubjectscore)
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "update",
    possession: "any",
  })
  async updateGresubjectscore(
    @graphql.Args() args: UpdateGresubjectscoreArgs
  ): Promise<Gresubjectscore | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Gresubjectscore)
  @nestAccessControl.UseRoles({
    resource: "Gresubjectscore",
    action: "delete",
    possession: "any",
  })
  async deleteGresubjectscore(
    @graphql.Args() args: DeleteGresubjectscoreArgs
  ): Promise<Gresubjectscore | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
