/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateReviewPositiveFactorOtherArgs } from "./CreateReviewPositiveFactorOtherArgs";
import { UpdateReviewPositiveFactorOtherArgs } from "./UpdateReviewPositiveFactorOtherArgs";
import { DeleteReviewPositiveFactorOtherArgs } from "./DeleteReviewPositiveFactorOtherArgs";
import { ReviewPositiveFactorOtherCountArgs } from "./ReviewPositiveFactorOtherCountArgs";
import { ReviewPositiveFactorOtherFindManyArgs } from "./ReviewPositiveFactorOtherFindManyArgs";
import { ReviewPositiveFactorOtherFindUniqueArgs } from "./ReviewPositiveFactorOtherFindUniqueArgs";
import { ReviewPositiveFactorOther } from "./ReviewPositiveFactorOther";
import { ReviewPositiveFactorOtherService } from "../reviewPositiveFactorOther.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ReviewPositiveFactorOther)
export class ReviewPositiveFactorOtherResolverBase {
  constructor(
    protected readonly service: ReviewPositiveFactorOtherService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "read",
    possession: "any",
  })
  async _reviewPositiveFactorOthersMeta(
    @graphql.Args() args: ReviewPositiveFactorOtherCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ReviewPositiveFactorOther])
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "read",
    possession: "any",
  })
  async reviewPositiveFactorOthers(
    @graphql.Args() args: ReviewPositiveFactorOtherFindManyArgs
  ): Promise<ReviewPositiveFactorOther[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ReviewPositiveFactorOther, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "read",
    possession: "own",
  })
  async reviewPositiveFactorOther(
    @graphql.Args() args: ReviewPositiveFactorOtherFindUniqueArgs
  ): Promise<ReviewPositiveFactorOther | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReviewPositiveFactorOther)
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "create",
    possession: "any",
  })
  async createReviewPositiveFactorOther(
    @graphql.Args() args: CreateReviewPositiveFactorOtherArgs
  ): Promise<ReviewPositiveFactorOther> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReviewPositiveFactorOther)
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "update",
    possession: "any",
  })
  async updateReviewPositiveFactorOther(
    @graphql.Args() args: UpdateReviewPositiveFactorOtherArgs
  ): Promise<ReviewPositiveFactorOther | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ReviewPositiveFactorOther)
  @nestAccessControl.UseRoles({
    resource: "ReviewPositiveFactorOther",
    action: "delete",
    possession: "any",
  })
  async deleteReviewPositiveFactorOther(
    @graphql.Args() args: DeleteReviewPositiveFactorOtherArgs
  ): Promise<ReviewPositiveFactorOther | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
