/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateApplicationMergeFileArgs } from "./CreateApplicationMergeFileArgs";
import { UpdateApplicationMergeFileArgs } from "./UpdateApplicationMergeFileArgs";
import { DeleteApplicationMergeFileArgs } from "./DeleteApplicationMergeFileArgs";
import { ApplicationMergeFileCountArgs } from "./ApplicationMergeFileCountArgs";
import { ApplicationMergeFileFindManyArgs } from "./ApplicationMergeFileFindManyArgs";
import { ApplicationMergeFileFindUniqueArgs } from "./ApplicationMergeFileFindUniqueArgs";
import { ApplicationMergeFile } from "./ApplicationMergeFile";
import { ApplicationMergeFileService } from "../applicationMergeFile.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApplicationMergeFile)
export class ApplicationMergeFileResolverBase {
  constructor(
    protected readonly service: ApplicationMergeFileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "read",
    possession: "any",
  })
  async _applicationMergeFilesMeta(
    @graphql.Args() args: ApplicationMergeFileCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApplicationMergeFile])
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "read",
    possession: "any",
  })
  async applicationMergeFiles(
    @graphql.Args() args: ApplicationMergeFileFindManyArgs
  ): Promise<ApplicationMergeFile[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApplicationMergeFile, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "read",
    possession: "own",
  })
  async applicationMergeFile(
    @graphql.Args() args: ApplicationMergeFileFindUniqueArgs
  ): Promise<ApplicationMergeFile | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationMergeFile)
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "create",
    possession: "any",
  })
  async createApplicationMergeFile(
    @graphql.Args() args: CreateApplicationMergeFileArgs
  ): Promise<ApplicationMergeFile> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationMergeFile)
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "update",
    possession: "any",
  })
  async updateApplicationMergeFile(
    @graphql.Args() args: UpdateApplicationMergeFileArgs
  ): Promise<ApplicationMergeFile | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ApplicationMergeFile)
  @nestAccessControl.UseRoles({
    resource: "ApplicationMergeFile",
    action: "delete",
    possession: "any",
  })
  async deleteApplicationMergeFile(
    @graphql.Args() args: DeleteApplicationMergeFileArgs
  ): Promise<ApplicationMergeFile | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
