/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateDietrichRecognitionArgs } from "./CreateDietrichRecognitionArgs";
import { UpdateDietrichRecognitionArgs } from "./UpdateDietrichRecognitionArgs";
import { DeleteDietrichRecognitionArgs } from "./DeleteDietrichRecognitionArgs";
import { DietrichRecognitionCountArgs } from "./DietrichRecognitionCountArgs";
import { DietrichRecognitionFindManyArgs } from "./DietrichRecognitionFindManyArgs";
import { DietrichRecognitionFindUniqueArgs } from "./DietrichRecognitionFindUniqueArgs";
import { DietrichRecognition } from "./DietrichRecognition";
import { DietrichRecognitionService } from "../dietrichRecognition.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DietrichRecognition)
export class DietrichRecognitionResolverBase {
  constructor(
    protected readonly service: DietrichRecognitionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "read",
    possession: "any",
  })
  async _dietrichRecognitionsMeta(
    @graphql.Args() args: DietrichRecognitionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DietrichRecognition])
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "read",
    possession: "any",
  })
  async dietrichRecognitions(
    @graphql.Args() args: DietrichRecognitionFindManyArgs
  ): Promise<DietrichRecognition[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DietrichRecognition, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "read",
    possession: "own",
  })
  async dietrichRecognition(
    @graphql.Args() args: DietrichRecognitionFindUniqueArgs
  ): Promise<DietrichRecognition | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DietrichRecognition)
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "create",
    possession: "any",
  })
  async createDietrichRecognition(
    @graphql.Args() args: CreateDietrichRecognitionArgs
  ): Promise<DietrichRecognition> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DietrichRecognition)
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "update",
    possession: "any",
  })
  async updateDietrichRecognition(
    @graphql.Args() args: UpdateDietrichRecognitionArgs
  ): Promise<DietrichRecognition | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DietrichRecognition)
  @nestAccessControl.UseRoles({
    resource: "DietrichRecognition",
    action: "delete",
    possession: "any",
  })
  async deleteDietrichRecognition(
    @graphql.Args() args: DeleteDietrichRecognitionArgs
  ): Promise<DietrichRecognition | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
