/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateRegistrationFeePaymentArgs } from "./CreateRegistrationFeePaymentArgs";
import { UpdateRegistrationFeePaymentArgs } from "./UpdateRegistrationFeePaymentArgs";
import { DeleteRegistrationFeePaymentArgs } from "./DeleteRegistrationFeePaymentArgs";
import { RegistrationFeePaymentCountArgs } from "./RegistrationFeePaymentCountArgs";
import { RegistrationFeePaymentFindManyArgs } from "./RegistrationFeePaymentFindManyArgs";
import { RegistrationFeePaymentFindUniqueArgs } from "./RegistrationFeePaymentFindUniqueArgs";
import { RegistrationFeePayment } from "./RegistrationFeePayment";
import { RegistrationFeePaymentService } from "../registrationFeePayment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => RegistrationFeePayment)
export class RegistrationFeePaymentResolverBase {
  constructor(
    protected readonly service: RegistrationFeePaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "read",
    possession: "any",
  })
  async _registrationFeePaymentsMeta(
    @graphql.Args() args: RegistrationFeePaymentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [RegistrationFeePayment])
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "read",
    possession: "any",
  })
  async registrationFeePayments(
    @graphql.Args() args: RegistrationFeePaymentFindManyArgs
  ): Promise<RegistrationFeePayment[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => RegistrationFeePayment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "read",
    possession: "own",
  })
  async registrationFeePayment(
    @graphql.Args() args: RegistrationFeePaymentFindUniqueArgs
  ): Promise<RegistrationFeePayment | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => RegistrationFeePayment)
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "create",
    possession: "any",
  })
  async createRegistrationFeePayment(
    @graphql.Args() args: CreateRegistrationFeePaymentArgs
  ): Promise<RegistrationFeePayment> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => RegistrationFeePayment)
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "update",
    possession: "any",
  })
  async updateRegistrationFeePayment(
    @graphql.Args() args: UpdateRegistrationFeePaymentArgs
  ): Promise<RegistrationFeePayment | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => RegistrationFeePayment)
  @nestAccessControl.UseRoles({
    resource: "RegistrationFeePayment",
    action: "delete",
    possession: "any",
  })
  async deleteRegistrationFeePayment(
    @graphql.Args() args: DeleteRegistrationFeePaymentArgs
  ): Promise<RegistrationFeePayment | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
