/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateGenderArgs } from "./CreateGenderArgs";
import { UpdateGenderArgs } from "./UpdateGenderArgs";
import { DeleteGenderArgs } from "./DeleteGenderArgs";
import { GenderCountArgs } from "./GenderCountArgs";
import { GenderFindManyArgs } from "./GenderFindManyArgs";
import { GenderFindUniqueArgs } from "./GenderFindUniqueArgs";
import { Gender } from "./Gender";
import { GenderService } from "../gender.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Gender)
export class GenderResolverBase {
  constructor(
    protected readonly service: GenderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "read",
    possession: "any",
  })
  async _gendersMeta(
    @graphql.Args() args: GenderCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Gender])
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "read",
    possession: "any",
  })
  async genders(@graphql.Args() args: GenderFindManyArgs): Promise<Gender[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Gender, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "read",
    possession: "own",
  })
  async gender(
    @graphql.Args() args: GenderFindUniqueArgs
  ): Promise<Gender | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gender)
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "create",
    possession: "any",
  })
  async createGender(@graphql.Args() args: CreateGenderArgs): Promise<Gender> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Gender)
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "update",
    possession: "any",
  })
  async updateGender(
    @graphql.Args() args: UpdateGenderArgs
  ): Promise<Gender | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Gender)
  @nestAccessControl.UseRoles({
    resource: "Gender",
    action: "delete",
    possession: "any",
  })
  async deleteGender(
    @graphql.Args() args: DeleteGenderArgs
  ): Promise<Gender | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
