/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateMhciPrereqsStatusArgs } from "./CreateMhciPrereqsStatusArgs";
import { UpdateMhciPrereqsStatusArgs } from "./UpdateMhciPrereqsStatusArgs";
import { DeleteMhciPrereqsStatusArgs } from "./DeleteMhciPrereqsStatusArgs";
import { MhciPrereqsStatusCountArgs } from "./MhciPrereqsStatusCountArgs";
import { MhciPrereqsStatusFindManyArgs } from "./MhciPrereqsStatusFindManyArgs";
import { MhciPrereqsStatusFindUniqueArgs } from "./MhciPrereqsStatusFindUniqueArgs";
import { MhciPrereqsStatus } from "./MhciPrereqsStatus";
import { MhciPrereqsStatusService } from "../mhciPrereqsStatus.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MhciPrereqsStatus)
export class MhciPrereqsStatusResolverBase {
  constructor(
    protected readonly service: MhciPrereqsStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "read",
    possession: "any",
  })
  async _mhciPrereqsStatusesMeta(
    @graphql.Args() args: MhciPrereqsStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MhciPrereqsStatus])
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "read",
    possession: "any",
  })
  async mhciPrereqsStatuses(
    @graphql.Args() args: MhciPrereqsStatusFindManyArgs
  ): Promise<MhciPrereqsStatus[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MhciPrereqsStatus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "read",
    possession: "own",
  })
  async mhciPrereqsStatus(
    @graphql.Args() args: MhciPrereqsStatusFindUniqueArgs
  ): Promise<MhciPrereqsStatus | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MhciPrereqsStatus)
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "create",
    possession: "any",
  })
  async createMhciPrereqsStatus(
    @graphql.Args() args: CreateMhciPrereqsStatusArgs
  ): Promise<MhciPrereqsStatus> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MhciPrereqsStatus)
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "update",
    possession: "any",
  })
  async updateMhciPrereqsStatus(
    @graphql.Args() args: UpdateMhciPrereqsStatusArgs
  ): Promise<MhciPrereqsStatus | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MhciPrereqsStatus)
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsStatus",
    action: "delete",
    possession: "any",
  })
  async deleteMhciPrereqsStatus(
    @graphql.Args() args: DeleteMhciPrereqsStatusArgs
  ): Promise<MhciPrereqsStatus | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
