/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateLanguageAssessmentRatingArgs } from "./CreateLanguageAssessmentRatingArgs";
import { UpdateLanguageAssessmentRatingArgs } from "./UpdateLanguageAssessmentRatingArgs";
import { DeleteLanguageAssessmentRatingArgs } from "./DeleteLanguageAssessmentRatingArgs";
import { LanguageAssessmentRatingCountArgs } from "./LanguageAssessmentRatingCountArgs";
import { LanguageAssessmentRatingFindManyArgs } from "./LanguageAssessmentRatingFindManyArgs";
import { LanguageAssessmentRatingFindUniqueArgs } from "./LanguageAssessmentRatingFindUniqueArgs";
import { LanguageAssessmentRating } from "./LanguageAssessmentRating";
import { LanguageAssessmentRatingService } from "../languageAssessmentRating.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LanguageAssessmentRating)
export class LanguageAssessmentRatingResolverBase {
  constructor(
    protected readonly service: LanguageAssessmentRatingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "read",
    possession: "any",
  })
  async _languageAssessmentRatingsMeta(
    @graphql.Args() args: LanguageAssessmentRatingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LanguageAssessmentRating])
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "read",
    possession: "any",
  })
  async languageAssessmentRatings(
    @graphql.Args() args: LanguageAssessmentRatingFindManyArgs
  ): Promise<LanguageAssessmentRating[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LanguageAssessmentRating, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "read",
    possession: "own",
  })
  async languageAssessmentRating(
    @graphql.Args() args: LanguageAssessmentRatingFindUniqueArgs
  ): Promise<LanguageAssessmentRating | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LanguageAssessmentRating)
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "create",
    possession: "any",
  })
  async createLanguageAssessmentRating(
    @graphql.Args() args: CreateLanguageAssessmentRatingArgs
  ): Promise<LanguageAssessmentRating> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LanguageAssessmentRating)
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "update",
    possession: "any",
  })
  async updateLanguageAssessmentRating(
    @graphql.Args() args: UpdateLanguageAssessmentRatingArgs
  ): Promise<LanguageAssessmentRating | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LanguageAssessmentRating)
  @nestAccessControl.UseRoles({
    resource: "LanguageAssessmentRating",
    action: "delete",
    possession: "any",
  })
  async deleteLanguageAssessmentRating(
    @graphql.Args() args: DeleteLanguageAssessmentRatingArgs
  ): Promise<LanguageAssessmentRating | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
