/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateDietrichFinancialSupportArgs } from "./CreateDietrichFinancialSupportArgs";
import { UpdateDietrichFinancialSupportArgs } from "./UpdateDietrichFinancialSupportArgs";
import { DeleteDietrichFinancialSupportArgs } from "./DeleteDietrichFinancialSupportArgs";
import { DietrichFinancialSupportCountArgs } from "./DietrichFinancialSupportCountArgs";
import { DietrichFinancialSupportFindManyArgs } from "./DietrichFinancialSupportFindManyArgs";
import { DietrichFinancialSupportFindUniqueArgs } from "./DietrichFinancialSupportFindUniqueArgs";
import { DietrichFinancialSupport } from "./DietrichFinancialSupport";
import { DietrichFinancialSupportService } from "../dietrichFinancialSupport.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DietrichFinancialSupport)
export class DietrichFinancialSupportResolverBase {
  constructor(
    protected readonly service: DietrichFinancialSupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "read",
    possession: "any",
  })
  async _dietrichFinancialSupportsMeta(
    @graphql.Args() args: DietrichFinancialSupportCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DietrichFinancialSupport])
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "read",
    possession: "any",
  })
  async dietrichFinancialSupports(
    @graphql.Args() args: DietrichFinancialSupportFindManyArgs
  ): Promise<DietrichFinancialSupport[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DietrichFinancialSupport, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "read",
    possession: "own",
  })
  async dietrichFinancialSupport(
    @graphql.Args() args: DietrichFinancialSupportFindUniqueArgs
  ): Promise<DietrichFinancialSupport | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DietrichFinancialSupport)
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "create",
    possession: "any",
  })
  async createDietrichFinancialSupport(
    @graphql.Args() args: CreateDietrichFinancialSupportArgs
  ): Promise<DietrichFinancialSupport> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DietrichFinancialSupport)
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "update",
    possession: "any",
  })
  async updateDietrichFinancialSupport(
    @graphql.Args() args: UpdateDietrichFinancialSupportArgs
  ): Promise<DietrichFinancialSupport | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DietrichFinancialSupport)
  @nestAccessControl.UseRoles({
    resource: "DietrichFinancialSupport",
    action: "delete",
    possession: "any",
  })
  async deleteDietrichFinancialSupport(
    @graphql.Args() args: DeleteDietrichFinancialSupportArgs
  ): Promise<DietrichFinancialSupport | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
