/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSlateReviewArgs } from "./CreateSlateReviewArgs";
import { UpdateSlateReviewArgs } from "./UpdateSlateReviewArgs";
import { DeleteSlateReviewArgs } from "./DeleteSlateReviewArgs";
import { SlateReviewCountArgs } from "./SlateReviewCountArgs";
import { SlateReviewFindManyArgs } from "./SlateReviewFindManyArgs";
import { SlateReviewFindUniqueArgs } from "./SlateReviewFindUniqueArgs";
import { SlateReview } from "./SlateReview";
import { SlateReviewService } from "../slateReview.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SlateReview)
export class SlateReviewResolverBase {
  constructor(
    protected readonly service: SlateReviewService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "read",
    possession: "any",
  })
  async _slateReviewsMeta(
    @graphql.Args() args: SlateReviewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SlateReview])
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "read",
    possession: "any",
  })
  async slateReviews(
    @graphql.Args() args: SlateReviewFindManyArgs
  ): Promise<SlateReview[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SlateReview, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "read",
    possession: "own",
  })
  async slateReview(
    @graphql.Args() args: SlateReviewFindUniqueArgs
  ): Promise<SlateReview | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SlateReview)
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "create",
    possession: "any",
  })
  async createSlateReview(
    @graphql.Args() args: CreateSlateReviewArgs
  ): Promise<SlateReview> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SlateReview)
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "update",
    possession: "any",
  })
  async updateSlateReview(
    @graphql.Args() args: UpdateSlateReviewArgs
  ): Promise<SlateReview | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SlateReview)
  @nestAccessControl.UseRoles({
    resource: "SlateReview",
    action: "delete",
    possession: "any",
  })
  async deleteSlateReview(
    @graphql.Args() args: DeleteSlateReviewArgs
  ): Promise<SlateReview | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
