/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { Em2FinancialSupportService } from "../em2FinancialSupport.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Em2FinancialSupportCreateInput } from "./Em2FinancialSupportCreateInput";
import { Em2FinancialSupportWhereInput } from "./Em2FinancialSupportWhereInput";
import { Em2FinancialSupportWhereUniqueInput } from "./Em2FinancialSupportWhereUniqueInput";
import { Em2FinancialSupportFindManyArgs } from "./Em2FinancialSupportFindManyArgs";
import { Em2FinancialSupportUpdateInput } from "./Em2FinancialSupportUpdateInput";
import { Em2FinancialSupport } from "./Em2FinancialSupport";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class Em2FinancialSupportControllerBase {
  constructor(
    protected readonly service: Em2FinancialSupportService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Em2FinancialSupport })
  @nestAccessControl.UseRoles({
    resource: "Em2FinancialSupport",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: Em2FinancialSupportCreateInput
  ): Promise<Em2FinancialSupport> {
    return await this.service.create({
      data: data,
      select: {
        applicationId: true,
        applyOutsideSupportSource: true,
        applyOutsideSupportType: true,
        attendWithoutSupport: true,
        familySupportAmount: true,
        familySupportType: true,
        id: true,
        otherSupportSource: true,
        receiveOutsideSupportSource: true,
        receiveOutsideSupportType: true,
        requestAssistantship: true,
        requestConsideration: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Em2FinancialSupport] })
  @ApiNestedQuery(Em2FinancialSupportFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Em2FinancialSupport",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<Em2FinancialSupport[]> {
    const args = plainToClass(Em2FinancialSupportFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        applicationId: true,
        applyOutsideSupportSource: true,
        applyOutsideSupportType: true,
        attendWithoutSupport: true,
        familySupportAmount: true,
        familySupportType: true,
        id: true,
        otherSupportSource: true,
        receiveOutsideSupportSource: true,
        receiveOutsideSupportType: true,
        requestAssistantship: true,
        requestConsideration: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Em2FinancialSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Em2FinancialSupport",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: Em2FinancialSupportWhereUniqueInput
  ): Promise<Em2FinancialSupport | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        applicationId: true,
        applyOutsideSupportSource: true,
        applyOutsideSupportType: true,
        attendWithoutSupport: true,
        familySupportAmount: true,
        familySupportType: true,
        id: true,
        otherSupportSource: true,
        receiveOutsideSupportSource: true,
        receiveOutsideSupportType: true,
        requestAssistantship: true,
        requestConsideration: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Em2FinancialSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Em2FinancialSupport",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: Em2FinancialSupportWhereUniqueInput,
    @common.Body() data: Em2FinancialSupportUpdateInput
  ): Promise<Em2FinancialSupport | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          applicationId: true,
          applyOutsideSupportSource: true,
          applyOutsideSupportType: true,
          attendWithoutSupport: true,
          familySupportAmount: true,
          familySupportType: true,
          id: true,
          otherSupportSource: true,
          receiveOutsideSupportSource: true,
          receiveOutsideSupportType: true,
          requestAssistantship: true,
          requestConsideration: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Em2FinancialSupport })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Em2FinancialSupport",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: Em2FinancialSupportWhereUniqueInput
  ): Promise<Em2FinancialSupport | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          applicationId: true,
          applyOutsideSupportSource: true,
          applyOutsideSupportType: true,
          attendWithoutSupport: true,
          familySupportAmount: true,
          familySupportType: true,
          id: true,
          otherSupportSource: true,
          receiveOutsideSupportSource: true,
          receiveOutsideSupportType: true,
          requestAssistantship: true,
          requestConsideration: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
