/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateApplicationDecisionArgs } from "./CreateApplicationDecisionArgs";
import { UpdateApplicationDecisionArgs } from "./UpdateApplicationDecisionArgs";
import { DeleteApplicationDecisionArgs } from "./DeleteApplicationDecisionArgs";
import { ApplicationDecisionCountArgs } from "./ApplicationDecisionCountArgs";
import { ApplicationDecisionFindManyArgs } from "./ApplicationDecisionFindManyArgs";
import { ApplicationDecisionFindUniqueArgs } from "./ApplicationDecisionFindUniqueArgs";
import { ApplicationDecision } from "./ApplicationDecision";
import { ApplicationDecisionService } from "../applicationDecision.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApplicationDecision)
export class ApplicationDecisionResolverBase {
  constructor(
    protected readonly service: ApplicationDecisionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "read",
    possession: "any",
  })
  async _applicationDecisionsMeta(
    @graphql.Args() args: ApplicationDecisionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApplicationDecision])
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "read",
    possession: "any",
  })
  async applicationDecisions(
    @graphql.Args() args: ApplicationDecisionFindManyArgs
  ): Promise<ApplicationDecision[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApplicationDecision, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "read",
    possession: "own",
  })
  async applicationDecision(
    @graphql.Args() args: ApplicationDecisionFindUniqueArgs
  ): Promise<ApplicationDecision | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationDecision)
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "create",
    possession: "any",
  })
  async createApplicationDecision(
    @graphql.Args() args: CreateApplicationDecisionArgs
  ): Promise<ApplicationDecision> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ApplicationDecision)
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "update",
    possession: "any",
  })
  async updateApplicationDecision(
    @graphql.Args() args: UpdateApplicationDecisionArgs
  ): Promise<ApplicationDecision | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ApplicationDecision)
  @nestAccessControl.UseRoles({
    resource: "ApplicationDecision",
    action: "delete",
    possession: "any",
  })
  async deleteApplicationDecision(
    @graphql.Args() args: DeleteApplicationDecisionArgs
  ): Promise<ApplicationDecision | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
