/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MhciPrereqsReferenceService } from "../mhciPrereqsReference.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MhciPrereqsReferenceCreateInput } from "./MhciPrereqsReferenceCreateInput";
import { MhciPrereqsReferenceWhereInput } from "./MhciPrereqsReferenceWhereInput";
import { MhciPrereqsReferenceWhereUniqueInput } from "./MhciPrereqsReferenceWhereUniqueInput";
import { MhciPrereqsReferenceFindManyArgs } from "./MhciPrereqsReferenceFindManyArgs";
import { MhciPrereqsReferenceUpdateInput } from "./MhciPrereqsReferenceUpdateInput";
import { MhciPrereqsReference } from "./MhciPrereqsReference";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MhciPrereqsReferenceControllerBase {
  constructor(
    protected readonly service: MhciPrereqsReferenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MhciPrereqsReference })
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsReference",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: MhciPrereqsReferenceCreateInput
  ): Promise<MhciPrereqsReference> {
    return await this.service.create({
      data: data,
      select: {
        anovaComment: true,
        anova_knowledge: true,
        applicationId: true,
        content: true,
        datafileId: true,
        id: true,
        lastReminderSent: true,
        periodId: true,
        programId: true,
        refUserId: true,
        regressionComment: true,
        regression_knowledge: true,
        reminderSentCount: true,
        submitted: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MhciPrereqsReference] })
  @ApiNestedQuery(MhciPrereqsReferenceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsReference",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<MhciPrereqsReference[]> {
    const args = plainToClass(MhciPrereqsReferenceFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        anovaComment: true,
        anova_knowledge: true,
        applicationId: true,
        content: true,
        datafileId: true,
        id: true,
        lastReminderSent: true,
        periodId: true,
        programId: true,
        refUserId: true,
        regressionComment: true,
        regression_knowledge: true,
        reminderSentCount: true,
        submitted: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsReference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsReference",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: MhciPrereqsReferenceWhereUniqueInput
  ): Promise<MhciPrereqsReference | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        anovaComment: true,
        anova_knowledge: true,
        applicationId: true,
        content: true,
        datafileId: true,
        id: true,
        lastReminderSent: true,
        periodId: true,
        programId: true,
        refUserId: true,
        regressionComment: true,
        regression_knowledge: true,
        reminderSentCount: true,
        submitted: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsReference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsReference",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: MhciPrereqsReferenceWhereUniqueInput,
    @common.Body() data: MhciPrereqsReferenceUpdateInput
  ): Promise<MhciPrereqsReference | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          anovaComment: true,
          anova_knowledge: true,
          applicationId: true,
          content: true,
          datafileId: true,
          id: true,
          lastReminderSent: true,
          periodId: true,
          programId: true,
          refUserId: true,
          regressionComment: true,
          regression_knowledge: true,
          reminderSentCount: true,
          submitted: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MhciPrereqsReference })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MhciPrereqsReference",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: MhciPrereqsReferenceWhereUniqueInput
  ): Promise<MhciPrereqsReference | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          anovaComment: true,
          anova_knowledge: true,
          applicationId: true,
          content: true,
          datafileId: true,
          id: true,
          lastReminderSent: true,
          periodId: true,
          programId: true,
          refUserId: true,
          regressionComment: true,
          regression_knowledge: true,
          reminderSentCount: true,
          submitted: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
