import { LuApplicationProgramUpdateManyWithoutApplicationsInput } from "./LuApplicationProgramUpdateManyWithoutApplicationsInput";
import { PeriodApplicationUpdateManyWithoutApplicationsInput } from "./PeriodApplicationUpdateManyWithoutApplicationsInput";

export type ApplicationUpdateInput = {
  area1?: string | null;
  area2?: string | null;
  area3?: string | null;
  buckleywaive?: boolean | null;
  cnbc?: number | null;
  complete?: boolean;
  createdDate?: Date | null;
  crossDeptProgs?: string | null;
  crossDeptProgsOther?: string | null;
  cups?: boolean;
  curEnrolled?: string;
  hide?: boolean;
  honors?: string | null;
  invitationEmailSent?: string | null;
  luApplicationPrograms?: LuApplicationProgramUpdateManyWithoutApplicationsInput;
  mastersReviewWaiver?: boolean;
  name?: string;
  notificationsent?: Date | null;
  otherInst?: string | null;
  paid?: boolean;
  paymentamount?: number | null;
  paymentdate?: Date | null;
  paymenttype?: number | null;
  periodApplication?: PeriodApplicationUpdateManyWithoutApplicationsInput;
  pier?: boolean;
  portfolioLink?: string | null;
  portfolioPassword?: string | null;
  portfoliosubmitted?: boolean | null;
  previousCoursework?: number | null;
  recordsPermission?: string | null;
  recruitingEvent?: string | null;
  referralToProgram?: string | null;
  rejectionSent?: string | null;
  round2?: string | null;
  round3?: string | null;
  sentToProgram?: string;
  statementofpurpose?: string | null;
  studentCommit?: boolean;
  submitted?: boolean;
  submittedDate?: Date | null;
  userId?: number;
  waitlistSent?: string | null;
  waive?: boolean;
  waivedate?: Date | null;
  waiveHigherFee?: number;
  waiveToefl?: number | null;
  womenfellowship?: boolean;
};
