/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateLuUserDepartmentArgs } from "./CreateLuUserDepartmentArgs";
import { UpdateLuUserDepartmentArgs } from "./UpdateLuUserDepartmentArgs";
import { DeleteLuUserDepartmentArgs } from "./DeleteLuUserDepartmentArgs";
import { LuUserDepartmentCountArgs } from "./LuUserDepartmentCountArgs";
import { LuUserDepartmentFindManyArgs } from "./LuUserDepartmentFindManyArgs";
import { LuUserDepartmentFindUniqueArgs } from "./LuUserDepartmentFindUniqueArgs";
import { LuUserDepartment } from "./LuUserDepartment";
import { LuUserDepartmentService } from "../luUserDepartment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LuUserDepartment)
export class LuUserDepartmentResolverBase {
  constructor(
    protected readonly service: LuUserDepartmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "read",
    possession: "any",
  })
  async _luUserDepartmentsMeta(
    @graphql.Args() args: LuUserDepartmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LuUserDepartment])
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "read",
    possession: "any",
  })
  async luUserDepartments(
    @graphql.Args() args: LuUserDepartmentFindManyArgs
  ): Promise<LuUserDepartment[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LuUserDepartment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "read",
    possession: "own",
  })
  async luUserDepartment(
    @graphql.Args() args: LuUserDepartmentFindUniqueArgs
  ): Promise<LuUserDepartment | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LuUserDepartment)
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "create",
    possession: "any",
  })
  async createLuUserDepartment(
    @graphql.Args() args: CreateLuUserDepartmentArgs
  ): Promise<LuUserDepartment> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => LuUserDepartment)
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "update",
    possession: "any",
  })
  async updateLuUserDepartment(
    @graphql.Args() args: UpdateLuUserDepartmentArgs
  ): Promise<LuUserDepartment | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LuUserDepartment)
  @nestAccessControl.UseRoles({
    resource: "LuUserDepartment",
    action: "delete",
    possession: "any",
  })
  async deleteLuUserDepartment(
    @graphql.Args() args: DeleteLuUserDepartmentArgs
  ): Promise<LuUserDepartment | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
