/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UsersinstService } from "../usersinst.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UsersinstCreateInput } from "./UsersinstCreateInput";
import { UsersinstWhereInput } from "./UsersinstWhereInput";
import { UsersinstWhereUniqueInput } from "./UsersinstWhereUniqueInput";
import { UsersinstFindManyArgs } from "./UsersinstFindManyArgs";
import { UsersinstUpdateInput } from "./UsersinstUpdateInput";
import { Usersinst } from "./Usersinst";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UsersinstControllerBase {
  constructor(
    protected readonly service: UsersinstService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Usersinst })
  @nestAccessControl.UseRoles({
    resource: "Usersinst",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: UsersinstCreateInput): Promise<Usersinst> {
    return await this.service.create({
      data: data,
      select: {
        applicationId: true,
        classRank: true,
        collegeName: true,
        convertedGpa: true,
        datafileId: true,
        dateEntered: true,
        dateGrad: true,
        dateLeft: true,
        degree: true,
        educationtype: true,
        gpa: true,
        gpaMajor: true,
        gpaScale: true,
        id: true,
        instituteId: true,
        major1: true,
        major2: true,
        major3: true,
        minor1: true,
        minor2: true,
        transscriptreceived: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Usersinst] })
  @ApiNestedQuery(UsersinstFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Usersinst",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Usersinst[]> {
    const args = plainToClass(UsersinstFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        applicationId: true,
        classRank: true,
        collegeName: true,
        convertedGpa: true,
        datafileId: true,
        dateEntered: true,
        dateGrad: true,
        dateLeft: true,
        degree: true,
        educationtype: true,
        gpa: true,
        gpaMajor: true,
        gpaScale: true,
        id: true,
        instituteId: true,
        major1: true,
        major2: true,
        major3: true,
        minor1: true,
        minor2: true,
        transscriptreceived: true,
        userId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Usersinst })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Usersinst",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UsersinstWhereUniqueInput
  ): Promise<Usersinst | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        applicationId: true,
        classRank: true,
        collegeName: true,
        convertedGpa: true,
        datafileId: true,
        dateEntered: true,
        dateGrad: true,
        dateLeft: true,
        degree: true,
        educationtype: true,
        gpa: true,
        gpaMajor: true,
        gpaScale: true,
        id: true,
        instituteId: true,
        major1: true,
        major2: true,
        major3: true,
        minor1: true,
        minor2: true,
        transscriptreceived: true,
        userId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Usersinst })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Usersinst",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: UsersinstWhereUniqueInput,
    @common.Body() data: UsersinstUpdateInput
  ): Promise<Usersinst | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          applicationId: true,
          classRank: true,
          collegeName: true,
          convertedGpa: true,
          datafileId: true,
          dateEntered: true,
          dateGrad: true,
          dateLeft: true,
          degree: true,
          educationtype: true,
          gpa: true,
          gpaMajor: true,
          gpaScale: true,
          id: true,
          instituteId: true,
          major1: true,
          major2: true,
          major3: true,
          minor1: true,
          minor2: true,
          transscriptreceived: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Usersinst })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Usersinst",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UsersinstWhereUniqueInput
  ): Promise<Usersinst | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          applicationId: true,
          classRank: true,
          collegeName: true,
          convertedGpa: true,
          datafileId: true,
          dateEntered: true,
          dateGrad: true,
          dateLeft: true,
          degree: true,
          educationtype: true,
          gpa: true,
          gpaMajor: true,
          gpaScale: true,
          id: true,
          instituteId: true,
          major1: true,
          major2: true,
          major3: true,
          minor1: true,
          minor2: true,
          transscriptreceived: true,
          userId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
