/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateUnitRoleArgs } from "./CreateUnitRoleArgs";
import { UpdateUnitRoleArgs } from "./UpdateUnitRoleArgs";
import { DeleteUnitRoleArgs } from "./DeleteUnitRoleArgs";
import { UnitRoleCountArgs } from "./UnitRoleCountArgs";
import { UnitRoleFindManyArgs } from "./UnitRoleFindManyArgs";
import { UnitRoleFindUniqueArgs } from "./UnitRoleFindUniqueArgs";
import { UnitRole } from "./UnitRole";
import { UnitRoleService } from "../unitRole.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UnitRole)
export class UnitRoleResolverBase {
  constructor(
    protected readonly service: UnitRoleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "read",
    possession: "any",
  })
  async _unitRolesMeta(
    @graphql.Args() args: UnitRoleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UnitRole])
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "read",
    possession: "any",
  })
  async unitRoles(
    @graphql.Args() args: UnitRoleFindManyArgs
  ): Promise<UnitRole[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UnitRole, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "read",
    possession: "own",
  })
  async unitRole(
    @graphql.Args() args: UnitRoleFindUniqueArgs
  ): Promise<UnitRole | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UnitRole)
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "create",
    possession: "any",
  })
  async createUnitRole(
    @graphql.Args() args: CreateUnitRoleArgs
  ): Promise<UnitRole> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UnitRole)
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "update",
    possession: "any",
  })
  async updateUnitRole(
    @graphql.Args() args: UpdateUnitRoleArgs
  ): Promise<UnitRole | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UnitRole)
  @nestAccessControl.UseRoles({
    resource: "UnitRole",
    action: "delete",
    possession: "any",
  })
  async deleteUnitRole(
    @graphql.Args() args: DeleteUnitRoleArgs
  ): Promise<UnitRole | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
