/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateDepartmentUnitArgs } from "./CreateDepartmentUnitArgs";
import { UpdateDepartmentUnitArgs } from "./UpdateDepartmentUnitArgs";
import { DeleteDepartmentUnitArgs } from "./DeleteDepartmentUnitArgs";
import { DepartmentUnitCountArgs } from "./DepartmentUnitCountArgs";
import { DepartmentUnitFindManyArgs } from "./DepartmentUnitFindManyArgs";
import { DepartmentUnitFindUniqueArgs } from "./DepartmentUnitFindUniqueArgs";
import { DepartmentUnit } from "./DepartmentUnit";
import { DepartmentUnitService } from "../departmentUnit.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DepartmentUnit)
export class DepartmentUnitResolverBase {
  constructor(
    protected readonly service: DepartmentUnitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "read",
    possession: "any",
  })
  async _departmentUnitsMeta(
    @graphql.Args() args: DepartmentUnitCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DepartmentUnit])
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "read",
    possession: "any",
  })
  async departmentUnits(
    @graphql.Args() args: DepartmentUnitFindManyArgs
  ): Promise<DepartmentUnit[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DepartmentUnit, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "read",
    possession: "own",
  })
  async departmentUnit(
    @graphql.Args() args: DepartmentUnitFindUniqueArgs
  ): Promise<DepartmentUnit | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DepartmentUnit)
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "create",
    possession: "any",
  })
  async createDepartmentUnit(
    @graphql.Args() args: CreateDepartmentUnitArgs
  ): Promise<DepartmentUnit> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DepartmentUnit)
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "update",
    possession: "any",
  })
  async updateDepartmentUnit(
    @graphql.Args() args: UpdateDepartmentUnitArgs
  ): Promise<DepartmentUnit | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DepartmentUnit)
  @nestAccessControl.UseRoles({
    resource: "DepartmentUnit",
    action: "delete",
    possession: "any",
  })
  async deleteDepartmentUnit(
    @graphql.Args() args: DeleteDepartmentUnitArgs
  ): Promise<DepartmentUnit | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
