/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateToeflItpPlusArgs } from "./CreateToeflItpPlusArgs";
import { UpdateToeflItpPlusArgs } from "./UpdateToeflItpPlusArgs";
import { DeleteToeflItpPlusArgs } from "./DeleteToeflItpPlusArgs";
import { ToeflItpPlusCountArgs } from "./ToeflItpPlusCountArgs";
import { ToeflItpPlusFindManyArgs } from "./ToeflItpPlusFindManyArgs";
import { ToeflItpPlusFindUniqueArgs } from "./ToeflItpPlusFindUniqueArgs";
import { ToeflItpPlus } from "./ToeflItpPlus";
import { ToeflItpPlusService } from "../toeflItpPlus.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ToeflItpPlus)
export class ToeflItpPlusResolverBase {
  constructor(
    protected readonly service: ToeflItpPlusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "read",
    possession: "any",
  })
  async _toeflItpPlusesMeta(
    @graphql.Args() args: ToeflItpPlusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ToeflItpPlus])
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "read",
    possession: "any",
  })
  async toeflItpPluses(
    @graphql.Args() args: ToeflItpPlusFindManyArgs
  ): Promise<ToeflItpPlus[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ToeflItpPlus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "read",
    possession: "own",
  })
  async toeflItpPlus(
    @graphql.Args() args: ToeflItpPlusFindUniqueArgs
  ): Promise<ToeflItpPlus | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ToeflItpPlus)
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "create",
    possession: "any",
  })
  async createToeflItpPlus(
    @graphql.Args() args: CreateToeflItpPlusArgs
  ): Promise<ToeflItpPlus> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ToeflItpPlus)
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "update",
    possession: "any",
  })
  async updateToeflItpPlus(
    @graphql.Args() args: UpdateToeflItpPlusArgs
  ): Promise<ToeflItpPlus | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ToeflItpPlus)
  @nestAccessControl.UseRoles({
    resource: "ToeflItpPlus",
    action: "delete",
    possession: "any",
  })
  async deleteToeflItpPlus(
    @graphql.Args() args: DeleteToeflItpPlusArgs
  ): Promise<ToeflItpPlus | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
