/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MlSupportingCourseworkService } from "../mlSupportingCoursework.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MlSupportingCourseworkCreateInput } from "./MlSupportingCourseworkCreateInput";
import { MlSupportingCourseworkWhereInput } from "./MlSupportingCourseworkWhereInput";
import { MlSupportingCourseworkWhereUniqueInput } from "./MlSupportingCourseworkWhereUniqueInput";
import { MlSupportingCourseworkFindManyArgs } from "./MlSupportingCourseworkFindManyArgs";
import { MlSupportingCourseworkUpdateInput } from "./MlSupportingCourseworkUpdateInput";
import { MlSupportingCoursework } from "./MlSupportingCoursework";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MlSupportingCourseworkControllerBase {
  constructor(
    protected readonly service: MlSupportingCourseworkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MlSupportingCoursework })
  @nestAccessControl.UseRoles({
    resource: "MlSupportingCoursework",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: MlSupportingCourseworkCreateInput
  ): Promise<MlSupportingCoursework> {
    return await this.service.create({
      data: data,
      select: {
        appId: true,
        id: true,
        introCourse2Grade: true,
        introCourse2Num: true,
        introCourse2Semester: true,
        introCourseGrade: true,
        introCourseNum: true,
        introCourseSemester: true,
        ml1CourseGrade: true,
        ml1CourseNum: true,
        ml1CourseSemester: true,
        ml2CourseGrade: true,
        ml2CourseNum: true,
        ml2CourseSemester: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MlSupportingCoursework] })
  @ApiNestedQuery(MlSupportingCourseworkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MlSupportingCoursework",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<MlSupportingCoursework[]> {
    const args = plainToClass(
      MlSupportingCourseworkFindManyArgs,
      request.query
    );
    return this.service.findMany({
      ...args,
      select: {
        appId: true,
        id: true,
        introCourse2Grade: true,
        introCourse2Num: true,
        introCourse2Semester: true,
        introCourseGrade: true,
        introCourseNum: true,
        introCourseSemester: true,
        ml1CourseGrade: true,
        ml1CourseNum: true,
        ml1CourseSemester: true,
        ml2CourseGrade: true,
        ml2CourseNum: true,
        ml2CourseSemester: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MlSupportingCoursework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MlSupportingCoursework",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: MlSupportingCourseworkWhereUniqueInput
  ): Promise<MlSupportingCoursework | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        appId: true,
        id: true,
        introCourse2Grade: true,
        introCourse2Num: true,
        introCourse2Semester: true,
        introCourseGrade: true,
        introCourseNum: true,
        introCourseSemester: true,
        ml1CourseGrade: true,
        ml1CourseNum: true,
        ml1CourseSemester: true,
        ml2CourseGrade: true,
        ml2CourseNum: true,
        ml2CourseSemester: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MlSupportingCoursework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MlSupportingCoursework",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: MlSupportingCourseworkWhereUniqueInput,
    @common.Body() data: MlSupportingCourseworkUpdateInput
  ): Promise<MlSupportingCoursework | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          appId: true,
          id: true,
          introCourse2Grade: true,
          introCourse2Num: true,
          introCourse2Semester: true,
          introCourseGrade: true,
          introCourseNum: true,
          introCourseSemester: true,
          ml1CourseGrade: true,
          ml1CourseNum: true,
          ml1CourseSemester: true,
          ml2CourseGrade: true,
          ml2CourseNum: true,
          ml2CourseSemester: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MlSupportingCoursework })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MlSupportingCoursework",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: MlSupportingCourseworkWhereUniqueInput
  ): Promise<MlSupportingCoursework | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          appId: true,
          id: true,
          introCourse2Grade: true,
          introCourse2Num: true,
          introCourse2Semester: true,
          introCourseGrade: true,
          introCourseNum: true,
          introCourseSemester: true,
          ml1CourseGrade: true,
          ml1CourseNum: true,
          ml1CourseSemester: true,
          ml2CourseGrade: true,
          ml2CourseNum: true,
          ml2CourseSemester: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
