/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserModelService } from "../userModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserModelCreateInput } from "./UserModelCreateInput";
import { UserModelWhereInput } from "./UserModelWhereInput";
import { UserModelWhereUniqueInput } from "./UserModelWhereUniqueInput";
import { UserModelFindManyArgs } from "./UserModelFindManyArgs";
import { UserModelUpdateInput } from "./UserModelUpdateInput";
import { UserModel } from "./UserModel";
import { LuUsersUsertypeFindManyArgs } from "../../luUsersUsertype/base/LuUsersUsertypeFindManyArgs";
import { LuUsersUsertype } from "../../luUsersUsertype/base/LuUsersUsertype";
import { LuUsersUsertypeWhereUniqueInput } from "../../luUsersUsertype/base/LuUsersUsertypeWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserModelControllerBase {
  constructor(
    protected readonly service: UserModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserModel })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: UserModelCreateInput): Promise<UserModel> {
    return await this.service.create({
      data: data,
      select: {
        email: true,
        firstname: true,
        guid: true,
        id: true,
        initials: true,
        lastname: true,
        middlename: true,
        password: true,
        signupDate: true,
        title: true,
        username: true,
        verified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserModel] })
  @ApiNestedQuery(UserModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<UserModel[]> {
    const args = plainToClass(UserModelFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        email: true,
        firstname: true,
        guid: true,
        id: true,
        initials: true,
        lastname: true,
        middlename: true,
        password: true,
        signupDate: true,
        title: true,
        username: true,
        verified: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: UserModelWhereUniqueInput
  ): Promise<UserModel | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        email: true,
        firstname: true,
        guid: true,
        id: true,
        initials: true,
        lastname: true,
        middlename: true,
        password: true,
        signupDate: true,
        title: true,
        username: true,
        verified: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: UserModelWhereUniqueInput,
    @common.Body() data: UserModelUpdateInput
  ): Promise<UserModel | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          email: true,
          firstname: true,
          guid: true,
          id: true,
          initials: true,
          lastname: true,
          middlename: true,
          password: true,
          signupDate: true,
          title: true,
          username: true,
          verified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: UserModelWhereUniqueInput
  ): Promise<UserModel | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          email: true,
          firstname: true,
          guid: true,
          id: true,
          initials: true,
          lastname: true,
          middlename: true,
          password: true,
          signupDate: true,
          title: true,
          username: true,
          verified: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/luUsersUsertypes")
  @ApiNestedQuery(LuUsersUsertypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LuUsersUsertype",
    action: "read",
    possession: "any",
  })
  async findManyLuUsersUsertypes(
    @common.Req() request: Request,
    @common.Param() params: UserModelWhereUniqueInput
  ): Promise<LuUsersUsertype[]> {
    const query = plainToClass(LuUsersUsertypeFindManyArgs, request.query);
    const results = await this.service.findLuUsersUsertypes(params.id, {
      ...query,
      select: {
        domain: true,
        id: true,

        users: {
          select: {
            id: true,
          },
        },

        usertypeId: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/luUsersUsertypes")
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "update",
    possession: "any",
  })
  async connectLuUsersUsertypes(
    @common.Param() params: UserModelWhereUniqueInput,
    @common.Body() body: LuUsersUsertypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      luUsersUsertypes: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/luUsersUsertypes")
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "update",
    possession: "any",
  })
  async updateLuUsersUsertypes(
    @common.Param() params: UserModelWhereUniqueInput,
    @common.Body() body: LuUsersUsertypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      luUsersUsertypes: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/luUsersUsertypes")
  @nestAccessControl.UseRoles({
    resource: "UserModel",
    action: "update",
    possession: "any",
  })
  async disconnectLuUsersUsertypes(
    @common.Param() params: UserModelWhereUniqueInput,
    @common.Body() body: LuUsersUsertypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      luUsersUsertypes: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
