/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PeriodService } from "../period.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PeriodCreateInput } from "./PeriodCreateInput";
import { PeriodWhereInput } from "./PeriodWhereInput";
import { PeriodWhereUniqueInput } from "./PeriodWhereUniqueInput";
import { PeriodFindManyArgs } from "./PeriodFindManyArgs";
import { PeriodUpdateInput } from "./PeriodUpdateInput";
import { Period } from "./Period";
import { PeriodApplicationFindManyArgs } from "../../periodApplication/base/PeriodApplicationFindManyArgs";
import { PeriodApplication } from "../../periodApplication/base/PeriodApplication";
import { PeriodApplicationWhereUniqueInput } from "../../periodApplication/base/PeriodApplicationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PeriodControllerBase {
  constructor(
    protected readonly service: PeriodService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Period })
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: PeriodCreateInput): Promise<Period> {
    return await this.service.create({
      data: data,
      select: {
        description: true,
        endDate: true,
        id: true,
        parentPeriodId: true,
        periodTypeId: true,
        startDate: true,
        unitId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Period] })
  @ApiNestedQuery(PeriodFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Period[]> {
    const args = plainToClass(PeriodFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        description: true,
        endDate: true,
        id: true,
        parentPeriodId: true,
        periodTypeId: true,
        startDate: true,
        unitId: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: PeriodWhereUniqueInput
  ): Promise<Period | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        description: true,
        endDate: true,
        id: true,
        parentPeriodId: true,
        periodTypeId: true,
        startDate: true,
        unitId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: PeriodWhereUniqueInput,
    @common.Body() data: PeriodUpdateInput
  ): Promise<Period | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          description: true,
          endDate: true,
          id: true,
          parentPeriodId: true,
          periodTypeId: true,
          startDate: true,
          unitId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Period })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: PeriodWhereUniqueInput
  ): Promise<Period | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          description: true,
          endDate: true,
          id: true,
          parentPeriodId: true,
          periodTypeId: true,
          startDate: true,
          unitId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/periodApplication")
  @ApiNestedQuery(PeriodApplicationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PeriodApplication",
    action: "read",
    possession: "any",
  })
  async findManyPeriodApplication(
    @common.Req() request: Request,
    @common.Param() params: PeriodWhereUniqueInput
  ): Promise<PeriodApplication[]> {
    const query = plainToClass(PeriodApplicationFindManyArgs, request.query);
    const results = await this.service.findPeriodApplication(params.id, {
      ...query,
      select: {
        application: {
          select: {
            id: true,
          },
        },

        id: true,

        period: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/periodApplication")
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "update",
    possession: "any",
  })
  async connectPeriodApplication(
    @common.Param() params: PeriodWhereUniqueInput,
    @common.Body() body: PeriodApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      periodApplication: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/periodApplication")
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "update",
    possession: "any",
  })
  async updatePeriodApplication(
    @common.Param() params: PeriodWhereUniqueInput,
    @common.Body() body: PeriodApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      periodApplication: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/periodApplication")
  @nestAccessControl.UseRoles({
    resource: "Period",
    action: "update",
    possession: "any",
  })
  async disconnectPeriodApplication(
    @common.Param() params: PeriodWhereUniqueInput,
    @common.Body() body: PeriodApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      periodApplication: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
