/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CcTransactionDetailService } from "../ccTransactionDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CcTransactionDetailCreateInput } from "./CcTransactionDetailCreateInput";
import { CcTransactionDetailWhereInput } from "./CcTransactionDetailWhereInput";
import { CcTransactionDetailWhereUniqueInput } from "./CcTransactionDetailWhereUniqueInput";
import { CcTransactionDetailFindManyArgs } from "./CcTransactionDetailFindManyArgs";
import { CcTransactionDetailUpdateInput } from "./CcTransactionDetailUpdateInput";
import { CcTransactionDetail } from "./CcTransactionDetail";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CcTransactionDetailControllerBase {
  constructor(
    protected readonly service: CcTransactionDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CcTransactionDetail })
  @nestAccessControl.UseRoles({
    resource: "CcTransactionDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: CcTransactionDetailCreateInput
  ): Promise<CcTransactionDetail> {
    return await this.service.create({
      data: data,
      select: {
        ccId: true,
        date: true,
        id: true,
        itemGlString: true,
        itemName: true,
        itemPriceEach: true,
        itemQty: true,
        paymentId: true,
        reportDate: true,
        time: true,
        transactionType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CcTransactionDetail] })
  @ApiNestedQuery(CcTransactionDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CcTransactionDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(
    @common.Req() request: Request
  ): Promise<CcTransactionDetail[]> {
    const args = plainToClass(CcTransactionDetailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        ccId: true,
        date: true,
        id: true,
        itemGlString: true,
        itemName: true,
        itemPriceEach: true,
        itemQty: true,
        paymentId: true,
        reportDate: true,
        time: true,
        transactionType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CcTransactionDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CcTransactionDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: CcTransactionDetailWhereUniqueInput
  ): Promise<CcTransactionDetail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        ccId: true,
        date: true,
        id: true,
        itemGlString: true,
        itemName: true,
        itemPriceEach: true,
        itemQty: true,
        paymentId: true,
        reportDate: true,
        time: true,
        transactionType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CcTransactionDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CcTransactionDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: CcTransactionDetailWhereUniqueInput,
    @common.Body() data: CcTransactionDetailUpdateInput
  ): Promise<CcTransactionDetail | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          ccId: true,
          date: true,
          id: true,
          itemGlString: true,
          itemName: true,
          itemPriceEach: true,
          itemQty: true,
          paymentId: true,
          reportDate: true,
          time: true,
          transactionType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CcTransactionDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CcTransactionDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: CcTransactionDetailWhereUniqueInput
  ): Promise<CcTransactionDetail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          ccId: true,
          date: true,
          id: true,
          itemGlString: true,
          itemName: true,
          itemPriceEach: true,
          itemQty: true,
          paymentId: true,
          reportDate: true,
          time: true,
          transactionType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
