/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateMitsSlateGreArgs } from "./CreateMitsSlateGreArgs";
import { UpdateMitsSlateGreArgs } from "./UpdateMitsSlateGreArgs";
import { DeleteMitsSlateGreArgs } from "./DeleteMitsSlateGreArgs";
import { MitsSlateGreCountArgs } from "./MitsSlateGreCountArgs";
import { MitsSlateGreFindManyArgs } from "./MitsSlateGreFindManyArgs";
import { MitsSlateGreFindUniqueArgs } from "./MitsSlateGreFindUniqueArgs";
import { MitsSlateGre } from "./MitsSlateGre";
import { MitsSlateGreService } from "../mitsSlateGre.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => MitsSlateGre)
export class MitsSlateGreResolverBase {
  constructor(
    protected readonly service: MitsSlateGreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "read",
    possession: "any",
  })
  async _mitsSlateGresMeta(
    @graphql.Args() args: MitsSlateGreCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [MitsSlateGre])
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "read",
    possession: "any",
  })
  async mitsSlateGres(
    @graphql.Args() args: MitsSlateGreFindManyArgs
  ): Promise<MitsSlateGre[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => MitsSlateGre, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "read",
    possession: "own",
  })
  async mitsSlateGre(
    @graphql.Args() args: MitsSlateGreFindUniqueArgs
  ): Promise<MitsSlateGre | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MitsSlateGre)
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "create",
    possession: "any",
  })
  async createMitsSlateGre(
    @graphql.Args() args: CreateMitsSlateGreArgs
  ): Promise<MitsSlateGre> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => MitsSlateGre)
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "update",
    possession: "any",
  })
  async updateMitsSlateGre(
    @graphql.Args() args: UpdateMitsSlateGreArgs
  ): Promise<MitsSlateGre | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MitsSlateGre)
  @nestAccessControl.UseRoles({
    resource: "MitsSlateGre",
    action: "delete",
    possession: "any",
  })
  async deleteMitsSlateGre(
    @graphql.Args() args: DeleteMitsSlateGreArgs
  ): Promise<MitsSlateGre | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
