/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateProgramGroupTypeArgs } from "./CreateProgramGroupTypeArgs";
import { UpdateProgramGroupTypeArgs } from "./UpdateProgramGroupTypeArgs";
import { DeleteProgramGroupTypeArgs } from "./DeleteProgramGroupTypeArgs";
import { ProgramGroupTypeCountArgs } from "./ProgramGroupTypeCountArgs";
import { ProgramGroupTypeFindManyArgs } from "./ProgramGroupTypeFindManyArgs";
import { ProgramGroupTypeFindUniqueArgs } from "./ProgramGroupTypeFindUniqueArgs";
import { ProgramGroupType } from "./ProgramGroupType";
import { ProgramGroupTypeService } from "../programGroupType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ProgramGroupType)
export class ProgramGroupTypeResolverBase {
  constructor(
    protected readonly service: ProgramGroupTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "read",
    possession: "any",
  })
  async _programGroupTypesMeta(
    @graphql.Args() args: ProgramGroupTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ProgramGroupType])
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "read",
    possession: "any",
  })
  async programGroupTypes(
    @graphql.Args() args: ProgramGroupTypeFindManyArgs
  ): Promise<ProgramGroupType[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ProgramGroupType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "read",
    possession: "own",
  })
  async programGroupType(
    @graphql.Args() args: ProgramGroupTypeFindUniqueArgs
  ): Promise<ProgramGroupType | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProgramGroupType)
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "create",
    possession: "any",
  })
  async createProgramGroupType(
    @graphql.Args() args: CreateProgramGroupTypeArgs
  ): Promise<ProgramGroupType> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ProgramGroupType)
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "update",
    possession: "any",
  })
  async updateProgramGroupType(
    @graphql.Args() args: UpdateProgramGroupTypeArgs
  ): Promise<ProgramGroupType | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ProgramGroupType)
  @nestAccessControl.UseRoles({
    resource: "ProgramGroupType",
    action: "delete",
    possession: "any",
  })
  async deleteProgramGroupType(
    @graphql.Args() args: DeleteProgramGroupTypeArgs
  ): Promise<ProgramGroupType | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
