/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateUsHSStatusArgs } from "./CreateUsHSStatusArgs";
import { UpdateUsHSStatusArgs } from "./UpdateUsHSStatusArgs";
import { DeleteUsHSStatusArgs } from "./DeleteUsHSStatusArgs";
import { UsHSStatusCountArgs } from "./UsHSStatusCountArgs";
import { UsHSStatusFindManyArgs } from "./UsHSStatusFindManyArgs";
import { UsHSStatusFindUniqueArgs } from "./UsHSStatusFindUniqueArgs";
import { UsHSStatus } from "./UsHSStatus";
import { UsHSStatusService } from "../usHsStatus.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UsHSStatus)
export class UsHSStatusResolverBase {
  constructor(
    protected readonly service: UsHSStatusService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "read",
    possession: "any",
  })
  async _usHsStatusesMeta(
    @graphql.Args() args: UsHSStatusCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UsHSStatus])
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "read",
    possession: "any",
  })
  async usHsStatuses(
    @graphql.Args() args: UsHSStatusFindManyArgs
  ): Promise<UsHSStatus[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UsHSStatus, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "read",
    possession: "own",
  })
  async usHsStatus(
    @graphql.Args() args: UsHSStatusFindUniqueArgs
  ): Promise<UsHSStatus | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UsHSStatus)
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "create",
    possession: "any",
  })
  async createUsHSStatus(
    @graphql.Args() args: CreateUsHSStatusArgs
  ): Promise<UsHSStatus> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UsHSStatus)
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "update",
    possession: "any",
  })
  async updateUsHSStatus(
    @graphql.Args() args: UpdateUsHSStatusArgs
  ): Promise<UsHSStatus | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UsHSStatus)
  @nestAccessControl.UseRoles({
    resource: "UsHSStatus",
    action: "delete",
    possession: "any",
  })
  async deleteUsHSStatus(
    @graphql.Args() args: DeleteUsHSStatusArgs
  ): Promise<UsHSStatus | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
